- hosts: all
  become: true
  vars:
    repository: "https://github.com/cass-dlcm/stat.ink.git"
    db_user: "statink"
    db_pass: "statink"
    db_database: "statink"
  roles:
    - env/osenv
    - env/user
    - env/node
    - env/pgsql
    - env/gearman
    - env/php
    - env/statink
    - app/database
    - app/app
    - app/h2o
