- name: Install RPM Remi-safe repo config
  yum:
    name: 'http://rpms.famillecollet.com/enterprise/remi-release-7.rpm'
    state: installed

- name: Install PHP packages
  yum:
    name:
      - php73-php-cli
      - php73-php-fpm
      - php73-php-gd
      - php73-php-intl
      - php73-php-json
      - php73-php-mbstring
      - php73-php-opcache
      - php73-php-pdo
      - php73-php-pecl-gearman
      - php73-php-pecl-msgpack
      - php73-php-pecl-zip
      - php73-php-pgsql
      - php73-php-process
      - php73-php-xml
      - php73-runtime
    state: installed

- name: Disable default config of PHP-FPM
  replace:
    dest: /etc/opt/remi/php73/php-fpm.d/www.conf
    regexp: '^(?!;)'
    replace: ';'

- name: Install config for PHP-FPM
  copy:
    src: statink.conf
    dest: /etc/opt/remi/php73/php-fpm.d/statink.conf

- name: Create directories for running PHP-FPM
  file:
    path: "{{ item }}"
    owner: statink
    group: statink
    state: directory
  with_items:
    - /var/www/statink/.php73-php-fpm/
    - /var/www/statink/.php73-php-fpm/session
    - /var/www/statink/.php73-php-fpm/wsdlcache

- name: Enable PHP-FPM
  systemd:
    name: php73-php-fpm.service
    enabled: true
    state: started

- name: Add PHP7.2 setting to /etc/profile.d
  copy:
    src: php73.sh
    dest: /etc/profile.d/php73.sh
