- name: Install RPM Remi-safe repo config
  yum:
    name: 'http://rpms.famillecollet.com/enterprise/remi-release-7.rpm'
    state: installed

- name: Install PHP packages
  yum:
    name:
      - php80-php-cli
      - php80-php-fpm
      - php80-php-gd
      - php80-php-intl
      - php80-php-mbstring
      - php80-php-opcache
      - php80-php-pdo
      - php80-php-pecl-gearman
      - php80-php-pecl-msgpack
      - php80-php-pecl-zip
      - php80-php-pgsql
      - php80-php-process
      - php80-php-sodium
      - php80-php-xml
      - php80-runtime
    state: installed

- name: Disable default config of PHP-FPM
  replace:
    dest: /etc/opt/remi/php80/php-fpm.d/www.conf
    regexp: '^(?!;)'
    replace: ';'

- name: Install config for PHP-FPM
  copy:
    src: statink.conf
    dest: /etc/opt/remi/php80/php-fpm.d/statink.conf

- name: Create directories for running PHP-FPM
  file:
    path: "{{ item }}"
    owner: statink
    group: statink
    state: directory
  with_items:
    - /var/www/statink/.php80-php-fpm/
    - /var/www/statink/.php80-php-fpm/session
    - /var/www/statink/.php80-php-fpm/wsdlcache

- name: Enable PHP-FPM
  systemd:
    name: php80-php-fpm.service
    enabled: true
    state: started

- name: Add PHP 8.0 setting to /etc/profile.d
  copy:
    src: php80.sh
    dest: /etc/profile.d/php80.sh
